services:
  mysql:
    image: mysql:8.0
    container_name: protegepet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - protege-pet-mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - protege-pet-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: protege-pet-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8080:80'
    networks:
      - protege-pet-network

volumes:
  protege-pet-mysql-data:
    driver: local

networks:
  protege-pet-network:
    driver: bridge
